version: "3"

services:
  wp-db:
    image: "postgres"
    container_name: "Library"
    environment:
      - POSTGRES_USER=wp
      - POSTGRES_PASSWORD=wp123
      - POSTGRES_DB=library
    ports:
      #      prvoto go menjas
      - "5430:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data